import { EventEmitter } from '@angular/core';
import { Subscription } from 'rxjs';
import { ProductBatchSerial } from './ProductBatchSerial';
import { BatchSelectorService } from './batchselector.service';
import { DatetimeService } from "xont-ventura-services";
export declare class XontVenturaBatchSelectorComponent {
    private batchSelectorService;
    private datetimeService;
    id: string;
    allowChange?: boolean;
    pageSize?: number;
    productCode?: string;
    productDesc?: string;
    onSelect: EventEmitter<ProductBatchSerial[]>;
    onCancel: EventEmitter<ProductBatchSerial[]>;
    private moveQty;
    private selectedQty;
    private decimalPlaces;
    private batchSearch;
    private numberFormat;
    batchSelectorMsgPrompt: any;
    busy: Subscription;
    currentBatchSerials: any[];
    constructor(batchSelectorService: BatchSelectorService, datetimeService: DatetimeService);
    ngOnInit(): void;
    ShowBatchSerials1(taskCode: string, territoryCode: string, warehouseCode: string, locationCode: string, productCode: string, requiredQty: number, uom: string, checkExpiryDate: boolean): void;
    ShowBatchSerials2(taskCode: string, territoryCode: string, warehouseCode: string, locationCode: string, productCode: string, requiredQty: number, uom: string, uom1: string, conversionFactor: number, reservedBatchSerials: ProductBatchSerial[], checkExpiryDate: boolean): void;
    ShowBatchSerials3(taskCode: string, territoryCode: string, warehouseCode: string, locationCode: string, productCode: string, requiredQty: number, uom: string, uom1: string, conversionFactor: number, autoSelect: boolean, checkExpiryDate: boolean): void;
    ShowBatchSerials4(taskCode: string, territoryCode: string, warehouseCode: string, locationCode: string, productCode: string, requiredQty: number, uom: string, uom1: string, conversionFactor: number, reservedBatchSerials: ProductBatchSerial[], selectedBatchSerials: ProductBatchSerial[], checkExpiryDate: boolean): void;
    ShowBatchSerials5(taskCode: string, territoryCode: string, warehouseCode: string, locationCode: string, productCode: string, requiredQty: number, uom: string, uom1: string, conversionFactor: number, reservedBatchSerials: ProductBatchSerial[], selectedBatchSerials: ProductBatchSerial[], addAllocated: boolean): void;
    private selectedQtyOnChange(item);
    private setSelectedQty();
    private chkOnChange(item);
    AutoSelectBatchesForManual(currentBatchSerials: any[], qty: number): ProductBatchSerial[];
    private cancel();
    private ok();
    private onSearch(event);
}
